name: Deploy to Azure
on:
  pull_request_target:
    types: [opened, synchronize]

env:
  NODE_VERSION: "18.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Test
        env:
          TEST_GITHUB_TOKEN: ${{ secrets.API_URL }}
          TEST_SECRET: ${{ secrets.API_URL_PLAYERS }}
        run: |
          echo ${#TEST_GITHUB_TOKEN}
          echo ${#TEST_SECRET}
      - run: node config.js
        env:
          API_URL: ${{ secrets.API_URL }}
          API_URL_PLAYERS: ${{ secrets.API_URL_PLAYERS }}
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run prod

      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
